FROM maven:3.9.9-eclipse-temurin-21 as builder

WORKDIR /app

COPY pom.xml .

RUN mvn dependency:go-offline -B

COPY src ./src

RUN mvn clean package

 \
FROM eclipse-temurin:21-jdk as runner

WORKDIR /app

COPY --from=builder ./app/target/*.jar app.jar

EXPOSE 4000

ENTRYPOINT ["java","-jar","app.jar"]